### ISSUE TITLE
Shell operator processing won't work with windows

### ISSUE THREAD

**Issue by ansrev** [homeport/havener#11]
_Update:_ In theory, we can support havener configuration files with `(( shell ... ))` operator that can do things in Windows. However, we have to discuss if it makes sense to put time into this since it is currently not a priority to have `havener` fully functional on Windows systems.

**Comment by ansrev** [comment]
I've tested executing commands on Windows, and it seems to be working. Depending on whether that's sufficient as a test or not, we can include the feature or drop it, your call.

**Comment by qu1queee** [comment]
I think we will drop windows support for now, due to time constraints. Thanks for checking this @ansrev

**Comment by HeavyWombat** [comment]
@ansrev very cool that you checked it for us. Let's stay in contact via Mail or Slack in case you want to continue to contribute with havener.
