### ISSUE TITLE
Change --tty flag to --no-tty flag to enable the TTY option as default

### ISSUE THREAD

**Issue by m-lukas** [homeport/havener#136]
This issue is related to the node-exec and pod-exec commands.
When using the default command (/bin/sh) or any similar command for opening a shell on the pod or node, it doesn't show the shell interface if the --tty flag is not set. Because it is more convenient to have it enabled by default, it makes sense to revert the flag meaning.

**Comment by HeavyWombat** [comment]
Fixed by #139
