### ISSUE TITLE
Remove --config flag from deploy and upgrade commands

### ISSUE THREAD

**Issue by m-lukas** [homeport/havener#169]
`deploy` and `upgrade` commands both need a path to a havener config file which is provided using the `--config` flag. While this creates symetries to `kubectl`, it creates a mandatory flag that has to be provided on every execution. Hence, the `--config` flag could be removed and replaced by an argument. This would shorten and simplify the contract but move away from the `kubectl` similarity. Altough, would that make sense?

Example: `havener deploy ./minikube-config.yml`

**Comment by HeavyWombat** [comment]
Yes, this sounds like a good idea. We should remove the `--config` flag.
