### ISSUE TITLE
Install tiller if not available

### ISSUE THREAD

**Issue by HeavyWombat** [homeport/havener#20]
On a fresh cluster (e.g. `minikube`), there is not set-up for helm available. This means there is no `tiller` pod.

**Proposal:** Perform something like `helm init` as part of `havener` for the deploy command.

**Comment by edwardstudy** [comment]
@qu1queee Hi, Enrique. Could I participate in this story? I am not sure that it is duplicate with you if I work on this.

**Comment by qu1queee** [comment]
of course, all yours @edwardstudy
