### ISSUE TITLE
neat.Table styl options leading to errors

### ISSUE THREAD

**Issue by qu1queee** [homeport/havener#215]
**Describe the bug**
current hvr version have issues when using watch, it seems related to the terminal size, specifically the following line: https://github.com/homeport/havener/blob/master/internal/cmd/watch.go#L227

The error I see is:
```
╭ Error occurred
│ unable to render table, the provided row limit of 25 exceeds the number of rows 16
╵
```

**To Reproduce**
I guess it depends on the terminal of the user, so is hard to say. 

**Expected behavior**
Ability to watch resources without a problem.

**Screenshots**

**Additional context**

**Comment by HeavyWombat** [comment]
Should be fixed by a bump of `neat` package version.
