### ISSUE TITLE
Spinner elapsed time should jump to minutes

### ISSUE THREAD

**Issue by qu1queee** [homeport/havener#28]
Change spinner elapsed time to display minutes instead of 234 s.

**Comment by HeavyWombat** [comment]
I have a look if I can bump to [gonvenience v1.3](https://github.com/homeport/gonvenience/releases/tag/v1.3) later this day, which fixes the elapsed time output.

**Comment by HeavyWombat** [comment]
Fix with https://github.com/homeport/havener/commit/91f5b3a663848a3f3fa9b46ea06f58dc0015fca4
