### ISSUE TITLE
Issue with node taints

### ISSUE THREAD

**Issue by HeavyWombat** [homeport/havener#386]
**Describe the bug**
The `havener` `node-exec` does not work with `taints` properly.

**To Reproduce**
1. Use a cluster with node taints
2. Run `havener ne <node> uptime`

**Expected behavior**
It should be able to place a pod on a given node.

**Screenshots**
n/a

**Additional context**
n/a

**Comment by qu1queee** [comment]
See https://github.com/homeport/havener/compare/qu1queee/label_selector_exec?expand=1 for an idea on what is needed
