### ISSUE TITLE
Add pkg versioning

### ISSUE THREAD

**Issue by qu1queee** [homeport/havener#4]
There are two major dependencies with delicate versioning requirements: `client-go` and `helm`. It could be that we have to introduce a versioning of the `havener` package itself to reflect that different versions of that are required to match with code with specific Kubernetes API packages, or `helm`.

So far we have not hit an issue so far, but it would be nice to discuss this issue and potential problems.

**Comment by HeavyWombat** [comment]
Luckily, this is not required anymore.
