### ISSUE TITLE
GKE cluster: no auth provider gcp

### ISSUE THREAD

**Issue by b4nst** [homeport/havener#420]
**Describe the bug**
Fail to use gcp auth provider for GKE cluster.

**To Reproduce**
1. Connect to GKE cluster
2. run `havener top`

**Expected behavior**
Overview of the current cluster usage details 

**Screenshots**
```
 Error: unable to get access to cluster
│ no Auth Provider found for name "gcp"
```

**Comment by kholloway** [comment]
Simple local fix is to add the single line below to `pkg/havener/common.go` right after [line 30](https://github.com/homeport/havener/blob/main/pkg/havener/common.go#L30) 

```
_ "k8s.io/client-go/plugin/pkg/client/auth/gcp"
```

Then rebuild locally with:

```
go build -o havener ./cmd/havener/main.go
```

You might get some go warnings about missing modules, just add them as the output tells you to and run build again.

**Comment by HeavyWombat** [comment]
Thanks for the hint. This will be added. I cannot promise anything, but I will try to release something tomorrow.
