### ISSUE TITLE
Is it possible to have a new parameter for top command so that just show one time

### ISSUE THREAD

**Issue by zhangtbj** [homeport/havener#59]
Right now, the `havener top` command will keep reporting `top` result.

I think in the future, it can be automated so that an automation script run one time to save the result for debugging or just for show for us.

So keep reporting may not work for that. Can we add a new parameter for example `havener top -n 1` to just show the result 1 or x times?

**Comment by HeavyWombat** [comment]
Absolutely, this is possible. Thanks for the input.

**Comment by HeavyWombat** [comment]
Absolutely, this is possible. Thanks for the input.

**Comment by HeavyWombat** [comment]
@zhangtbj will be fixed in the next release.
